[profile.default]
src = "src"
out = "out"
libs = ["lib"]

optimizer = true
optimizer_runs = 200
via_ir = true

remappings = [
	"@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
	"account-abstraction/=lib/account-abstraction/contracts/",
	"forge-std/=lib/forge-std/src/",
	"openzeppelin-contracts/=lib/openzeppelin-contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
